-- Comando SQL item a)
SELECT C.CD_CATEGORIA,INITCAP (C.DS_CATEGORIA), P.CD_CATEGORIA, P.CD_PRODUTO, P.VL_UNITARIO, P.DS_PRODUTO, P.TP_EMBALAGEM, P.VL_PERC_LUCRO
FROM MC_PRODUTO P, MC_CATEGORIA_PROD C
WHERE C.CD_CATEGORIA = P.CD_CATEGORIA
ORDER BY C.DS_CATEGORIA, P.DS_PRODUTO ASC; 
    
-- Comando SQL item b)
/*
SELECT F.DT_NASCIMENTO, INITCAP(TO_CHAR(F.DT_NASCIMENTO,'DAY')) AS ANIVER, SYSDATE, CONCAT(ROUND((SYSDATE-F.DT_NASCIMENTO)/30/12,0), ' Anos') AS IDADE 
    FROM MC_CLI_FISICA F;*/
    
SELECT C.NR_CLIENTE as "Cod Cliente", 
       C.DS_EMAIL as " Email" , 
       C.NR_TELEFONE as "Telefone", 
       C.NM_LOGIN as "Login", 
       F.DT_NASCIMENTO as " Dt Nascimento", 
       INITCAP(TO_CHAR(F.DT_NASCIMENTO,'DAY')) AS "Semana Nascimento",
       CONCAT(ROUND((SYSDATE-F.DT_NASCIMENTO)/30/12,0), ' Anos') AS "Idade", 
       F.FL_SEXO_BIOLOGICO as " Sexo B.", 
       F.NR_CPF as "CPF"
FROM MC_CLIENTE C, MC_CLI_FISICA F
WHERE C.NR_CLIENTE = F.NR_CLIENTE; 

-- Comando SQL item c)
/*SELECT TABLE_NAME FROM USER_TABLES
SELECT * FROM MC_SGV_VISUALIZACAO_VIDEO*/

SELECT P.CD_PRODUTO AS "Codigo do Produto", 
       INITCAP(P.DS_PRODUTO) AS "Descricao do Produto", 
       V.DT_VISUALIZACAO AS "Data da Visualizacao ", 
       V.NR_HORA_VISUALIZACAO AS "Hora da Visualizacao"
FROM MC_SGV_VISUALIZACAO_VIDEO V, MC_PRODUTO P
WHERE V.CD_PRODUTO = P.CD_PRODUTO
ORDER BY V.DT_VISUALIZACAO, V.NR_HORA_VISUALIZACAO DESC;